### ISSUE TITLE
Undefined property: App\Http\Controllers\HomeController::$app

### ISSUE THREAD

**Issue by bbjansen** [findbrok/laravel-personality-insights#21]
What and where do I define? I'm running into some issues with your documentation. Thanks!

**Comment by betd-pmamedy** [comment]
This is not related to the Package. Make sure you define your variables in your controller. Follow the Laravel Documentation for more info on Service Container before going further.

**Comment by percymamedy** [comment]
Not related to the Package. I advise you to learn more about the Laravel IOC container and make sure you have a grasp of how to it works before using the Package.
