### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by percymamedy** [findbrok/laravel-personality-insights#22]
Help needed to complete the Documentation for version 1.1

**Comment by Sk8rSeth** [comment]
what sort of documentation are we talking about here? code documentation? like documenting functions and code snippets, or documentation like whats in the README to help new users navigate this project on the outside of the code?

**Comment by percymamedy** [comment]
Usage documentation to help developers use the project. Same a for version 1.0 [here](https://github.com/findbrok/laravel-personality-insights/wiki/Documentation-1.0). Version [1.1](https://github.com/findbrok/laravel-personality-insights/wiki/Documentation-1.1) needs docs needs completion.
