### ISSUE TITLE
query parameter not appending correctly to request

### ISSUE THREAD

**Issue by robertsky** [findbrok/laravel-personality-insights#8]
Using v3 api, there is a need to append query parameter: 'version' to the request, otherwise it will throw out the following error on response:
`{
	"code": 400,
	"sub_code": "S00016",
	"error": "No version provided"
}`

Your documentation/wiki isn't up to date with your latest changes and probably with the changes between v2 and v3 api sets as well. After a couple of days of debugging, packet sniffing through a proxy and comparing with raw cURL requests I crafted, I found that the query parameter isn't appended correct, thus malforming the request URL.

Expected URL: https://gateway.watsonplatform.net/personality-insights/api/v3/profile?version=2017-03-10&
Actual URL: https://gateway.watsonplatform.net/personality-insights/api/v3/profileversion=2017-03-10&
Note: the extra '&' character is not required, a minor bug, but the request will go through still

**Comment by percymamedy** [comment]
Thank you!!... I have merged ur changes and will make a new release for it....

Yes I haven't had time to update the documentation yet since I had to release the new version to support v3 of Personality insights as IBM was deprecating v2.

But I am working on it.... I welcome any help and contributions on docs and code.

Thanks again.

**Comment by robertsky** [comment]
> I welcome any help and contributions on docs and code.

@percymamedy i don't mind helping out. 😄  As mentioned I am building up a demo. Though I can't open source it, I should be able to help out with the docs and the codes still.

**Comment by percymamedy** [comment]
@robertsky great !!... I have made a new release [v1.1.3](https://github.com/findbrok/laravel-personality-insights/releases/tag/v1.1.3) with your fixes.

Thanks again.. And if u want to contribute more to the package.. My door is always open..

:smile:

**Comment by robertsky** [comment]
I suppose I may soon again. I am trying to get the percentile out for a facet:

```
$insights = app()->make(PersonalityInsights::SERVICE_ID)->addContentItems($tweetsFormatted);
$profile = $insights->withQuery(array('version' => '2017-03-10'))->getFullProfile();
$result = $profile->findFacetByName('Susceptible to stress');
$percentage = $result->calculatePercentage();
```

The $personality variable has a Collection value, but I am getting this Exception:
`'Call to a member function calculatePercentage() on null'`

Advise?

**Comment by percymamedy** [comment]
Try ```findFacetById``` using ```facet_vulnerability``` as id.

**Comment by robertsky** [comment]
Same exception error.

**Comment by percymamedy** [comment]
Seems am also getting the same error... Am making some tests and trying to debug also... open a PR or Issue if u find something.. thanks.

**Comment by robertsky** [comment]
@percymamedy 1.1.4 works! thanks!
